### PR TITLE
Deprecate Otto in favor of RxJava

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by gfx** [comment]
Oh, really?

Is there any example to replace Otto with RxJava?

**Comment by swankjesse** [comment]
It's not a direct conversion. But Rx is capable of the same kinds of decoupling events as Otto.

**Comment by gfx** [comment]
I think RxJava subjects are good replacement of Otto in some cases, but if you think Otto is deprecated, you'd better to explain how to.

**Comment by swankjesse** [comment]
Thus post from @kaushikgopal is a good place to start.
http://nerds.weddingpartyapp.com/tech/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/

**Comment by gfx** [comment]
Thanks. Can you add it to README please?

**Comment by Tolriq** [comment]
@swankjesse Is there any advice / tips on the producer pattern (@Produce) with RxJava can't seem to find related docs ?

**Comment by JakeWharton** [comment]
All observables are producers in some sense as subscription is what causes
events to start flowing to the subscriber.

**Comment by Giszmo** [comment]
I strongly disagree with deprecation in absence of a lean replacement.

````
eventBus.register(this);
...
@Subscribe
public void somethingHappened(SomeEvent event) {
// do something
}
````

is **not** the same as 

````
eventBus
    .observable(SomeEvent.class)
    .subscribe(event -> {
      // do something
    });
````

not to talk about the worse "replacements" I found, with `instanceof` checks.

**Pull request merged**
